swagger: '2.0'
info:
  title: Session Monitoring REST
  description: Session Monitoring REST
  version: development
paths:
  /events:
    get:
      summary: Gets events for the project
      produces:
        - application/json
      parameters:
        - name: event
          in: query
          description: event names that need to be filtered
          required: false
          type: array
          items:
            type: string
            enum:
              - connectionCreated
              - connectionDestroyed
              - streamCreated
              - streamDestroyed
            default: All events will be returned
        - name: since
          in: query
          description: Lower bound on the time of event. Events returned will not be earlier than this timestamp.
          required: false
          type: integer
      responses:
        '200':
          description: 'Everything''s shiny, Captain, not to fret.'
          examples:
            application/json: |
              {
                "events": [
                  {
                    "sessionId": "2_MX4xMzExMjU3MX5-MTQ3MDI1NzY3OTkxOH45QXRr",
                    "projectId": "123456",
                    "event": "connectionCreated",
                    "timestamp": 1470257688309,
                    "connection": {
                      "id": "c053fcc8-c681-41d5-8ec2-7a9e1434a21e",
                      "createdAt": 1470257688143,
                      "data": "TOKENDATA"
                    }
                  }
                ]
              }
