swagger: '2.0'
info:
  title: Web-based composition API
  description: |
    # Introduction


  version: development
host: 127.0.0.1
basePath: /
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json

################################################################################
tags:
  - name: Advanced Layout Control
    description: Web-based archiving

################################################################################

parameters:
  jobId:
    name: id
    in: path
    description: The identifier for this job
    type: string
    required: true

################################################################################
